/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.nevilon.bigplanet;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int archive=0x7f020000;
        public static final int bookmark=0x7f020001;
        public static final int database_up=0x7f020002;
        public static final int delete=0x7f020003;
        public static final int edit=0x7f020004;
        public static final int globe=0x7f020005;
        public static final int globe_download=0x7f020006;
        public static final int globe_process=0x7f020007;
        public static final int home=0x7f020008;
        public static final int icon=0x7f020009;
        public static final int mode=0x7f02000a;
        public static final int notification_done=0x7f02000b;
        public static final int ok=0x7f02000c;
        public static final int small=0x7f02000d;
        public static final int tools=0x7f02000e;
    }
    public static final class id {
        public static final int addBtn=0x7f050005;
        public static final int cancelBtn=0x7f050006;
        public static final int cancelButton=0x7f05000b;
        public static final int descriptionValue=0x7f050003;
        public static final int descriptionkLabel=0x7f050002;
        public static final int downloadInfo=0x7f050009;
        public static final int nameLabel=0x7f050000;
        public static final int nameValue=0x7f050001;
        public static final int radiusLabel=0x7f050008;
        public static final int radiusSeekbar=0x7f050007;
        public static final int startButton=0x7f05000a;
        public static final int validationError=0x7f050004;
    }
    public static final class layout {
        public static final int addgeobookmark=0x7f030000;
        public static final int geobookmark=0x7f030001;
        public static final int main=0x7f030002;
        public static final int savemap=0x7f030003;
    }
    public static final class string {
        public static final int GOOGLE_SATELLITE=0x7f040004;
        public static final int GOOGLE_VECTOR=0x7f040005;
        public static final int OPENSTREET_VECTOR=0x7f040001;
        public static final int YANDEX_SATELLITE=0x7f040002;
        public static final int YANDEX_VECTOR=0x7f040003;
        public static final int app_name=0x7f040000;
    }
}
