/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.nevilon.moow;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int big=0x7f020000;
        public static final int icon=0x7f020001;
    }
    public static final class id {
        public static final int cancelButton=0x7f050005;
        public static final int downloadInfo=0x7f050003;
        public static final int radiusLabel=0x7f050001;
        public static final int radiusSeekbar=0x7f050000;
        public static final int radiusValue=0x7f050002;
        public static final int startButton=0x7f050004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int savemap=0x7f030001;
    }
    public static final class string {
        public static final int GOOGLE_SATELLITE=0x7f040005;
        public static final int GOOGLE_VECTOR=0x7f040006;
        public static final int OPENSTREET_VECTOR=0x7f040002;
        public static final int YANDEX_SATELLITE=0x7f040003;
        public static final int YANDEX_VECTOR=0x7f040004;
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
