/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.nevilon.bigplanet;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int archive=0x7f020000;
        public static final int bookmark=0x7f020001;
        public static final int bookmark_marker=0x7f020002;
        public static final int comment=0x7f020003;
        public static final int current_postion=0x7f020004;
        public static final int database_up=0x7f020005;
        public static final int delete=0x7f020006;
        public static final int edit=0x7f020007;
        public static final int globe=0x7f020008;
        public static final int globe_download=0x7f020009;
        public static final int globe_process=0x7f02000a;
        public static final int home=0x7f02000b;
        public static final int icon=0x7f02000c;
        public static final int info=0x7f02000d;
        public static final int location_marker=0x7f02000e;
        public static final int marker=0x7f02000f;
        public static final int marker2=0x7f020010;
        public static final int mode=0x7f020011;
        public static final int notification_done=0x7f020012;
        public static final int ok=0x7f020013;
        public static final int search=0x7f020014;
        public static final int small=0x7f020015;
        public static final int tools=0x7f020016;
    }
    public static final class id {
        public static final int addBtn=0x7f060005;
        public static final int body=0x7f060009;
        public static final int cancelBtn=0x7f060006;
        public static final int cancelButton=0x7f06000e;
        public static final int descriptionValue=0x7f060003;
        public static final int descriptionkLabel=0x7f060002;
        public static final int downloadInfo=0x7f06000c;
        public static final int message=0x7f060007;
        public static final int nameLabel=0x7f060000;
        public static final int nameValue=0x7f060001;
        public static final int okBtn=0x7f060008;
        public static final int radiusLabel=0x7f06000b;
        public static final int radiusSeekbar=0x7f06000a;
        public static final int startButton=0x7f06000d;
        public static final int validationError=0x7f060004;
    }
    public static final class layout {
        public static final int addgeobookmark=0x7f030000;
        public static final int demodialog=0x7f030001;
        public static final int geobookmark=0x7f030002;
        public static final int main=0x7f030003;
        public static final int progress_dialog=0x7f030004;
        public static final int savemap=0x7f030005;
    }
    public static final class string {
        public static final int ABOUT_MENU=0x7f050012;
        public static final int ABOUT_MESSAGE=0x7f050027;
        public static final int ABOUT_TITLE=0x7f050028;
        public static final int ADD_BOOKMARK_TITLE=0x7f050022;
        public static final int ADD_BUTTON=0x7f05000d;
        public static final int BOOKMARKS_MENU=0x7f050017;
        public static final int BOOKMARKS_VIEW_MENU=0x7f050019;
        public static final int BOOKMARK_ADD_MENU=0x7f050018;
        public static final int CACHE_MAP_MENU=0x7f050015;
        public static final int CANCEL_LABEL=0x7f05000c;
        public static final int DELETE_MENU=0x7f050008;
        public static final int DOWNLOAD_COMPLETE_MESSAGE=0x7f050023;
        public static final int DOWNLOAD_COMPLETE_TITLE=0x7f050021;
        public static final int DOWNLOAD_IN_PROGRESS_MESSAGE=0x7f050025;
        public static final int DOWNLOAD_MESSAGE_PATTERN=0x7f05001f;
        public static final int DOWNLOAD_PROGRESS_MESSAGE_PATTERN=0x7f050026;
        public static final int EDIT_MENU=0x7f050007;
        public static final int EMPTY_NAME_ERROR=0x7f050024;
        public static final int MAP_SOURCE_MENU=0x7f050013;
        public static final int NETWORK_MODE_MENU=0x7f050016;
        public static final int NO_LABEL=0x7f05000a;
        public static final int OFFLINE_MODE_LABEL=0x7f05001c;
        public static final int OK_LABEL=0x7f05000b;
        public static final int ONLINE_MODE_LABEL=0x7f05001d;
        public static final int REGION_RADIUS_TITLE=0x7f050020;
        public static final int REMOVE_BOOKMARK_MESSAGE=0x7f050010;
        public static final int REMOVE_BOOKMARK_TITLE=0x7f05000f;
        public static final int SAVE_BUTTON=0x7f05000e;
        public static final int SEARCH_MENU=0x7f050011;
        public static final int SELECT_MAP_SOURCE_TITLE=0x7f05001e;
        public static final int SELECT_NETWORK_MODE_LABEL=0x7f05001b;
        public static final int SELECT_OBJECT_MESSAGE=0x7f05001a;
        public static final int TOOLS_MENU=0x7f050014;
        public static final int YES_LABEL=0x7f050009;
        public static final int app_name=0x7f050006;
        public static final int search_hint=0x7f050005;
        public static final int search_label=0x7f050004;
        public static final int this_is_demo_message=0x7f050003;
        public static final int this_is_demo_title=0x7f050002;
        public static final int try_demo_message=0x7f050001;
        public static final int try_demo_title=0x7f050000;
    }
    public static final class xml {
        public static final int searchable=0x7f040000;
    }
}
